slam_toolbox:
  ros__parameters:
    # 坐标系配置（需与机器人实际坐标系匹配）
    map_frame: map              # 地图坐标系
    odom_frame: odom            # 里程计坐标系
    base_frame: base_link       # 机器人基坐标系
    scan_topic: /scan           # 激光雷达话题（需与实际发布的话题一致）
    
    # 地图参数
    resolution: 0.05            # 地图分辨率（米/像素）
    map_update_interval: 5.0    # 地图更新间隔（秒），值越小建图越实时但性能消耗大
    
    # 传感器数据处理
    max_laser_range: 10.0       # 激光最大有效距离（米）
    min_laser_range: 0.1        # 激光最小有效距离（米）
    laser_min_angle: -1.5708    # 激光最小角度（弧度，默认-90度）
    laser_max_angle: 1.5708     # 激光最大角度（弧度，默认90度）
    ignore_laser_scan_invalid: true  # 忽略无效的激光点
    
    # 粒子滤波参数（影响定位精度和性能）
    num_particles: 2000         # 粒子数量，环境复杂可增大（如3000）
    minimum_travel_distance: 0.2 # 触发更新的最小移动距离（米）
    minimum_travel_heading: 0.17 # 触发更新的最小旋转角度（弧度，约10度）
    
    # 匹配参数
    transform_publish_period: 0.05 # TF变换发布周期（秒）
    correlation_score_threshold: 0.7 # 匹配分数阈值，低于此值则认为匹配失败
    
    # 地图优化参数
    loop_closing: true          # 是否启用回环检测
    loop_search_radius: 3.0     # 回环检测搜索半径（米）
    loop_search_angle: 0.523    # 回环检测搜索角度（弧度，约30度）
    loop_closure_transform_threshold:
      translation: 0.1          # 回环检测平移阈值（米）
      rotation: 0.17            # 回环检测旋转阈值（弧度）
    
    # 调试参数
    debug_logging: false        # 是否启用调试日志
    publish_scan_matched_pose: true # 是否发布扫描匹配后的位姿
    use_scan_matching: true     # 是否使用扫描匹配
    use_exact_sync: false       # 是否使用精确的时间同步
    use_sim_time: true          # 是否使用仿真时间（Gazebo仿真时需设为true）
