controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    mecanum_controller:
      type: mecanum_controller/MecanumController

# 修正：mecanum_controller与joint_state_broadcaster同级（缩进2格）
joint_state_broadcaster:
  ros__parameters:
    joints:
      - left_front_wheel_joint
      - right_front_wheel_joint
      - left_rear_wheel_joint
      - right_rear_wheel_joint


mecanum_controller:
  ros__parameters:
    front_left_wheel_name: "left_front_wheel_joint"  # 直接给字符串值
    front_right_wheel_name: "right_front_wheel_joint"
    rear_left_wheel_name: "left_rear_wheel_joint"
    rear_right_wheel_name: "right_rear_wheel_joint"
    # 其他参数也需改为直接赋值格式
    wheel_separation_x: 0.08575
    wheel_separation_y: 0.09
    wheel_radius: 0.035
    tf_frame_prefix_enable: true
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    open_loop: false
    position_feedback: true
    enable_odom_tf: true
    cmd_vel_timeout: 0.05
    publish_rate: 50.0